customhost = "database-1.cvt8qbqpbpdh.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "deborahjoseph-employee"
customregion = "us-east-1"
